// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prisoners.Data.Models;

#nullable disable

namespace Prisoners.Data.Migrations
{
    [DbContext(typeof(PrisonContext))]
    partial class PrisonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Prisoners.Data.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("longtext");

                    b.Property<int>("PrisonerId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrisonerId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Prisoners.Data.Models.Prisoner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cellnumber")
                        .HasColumnType("int");

                    b.Property<string>("Crime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Prisoners");
                });

            modelBuilder.Entity("Prisoners.Data.Models.Inventory", b =>
                {
                    b.HasOne("Prisoners.Data.Models.Prisoner", null)
                        .WithMany("PrisonerInventories")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prisoners.Data.Models.Prisoner", b =>
                {
                    b.Navigation("PrisonerInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
